# 1. Setup and Load Data

In [1]:
# ====================================================
# Setup & Imports
# ====================================================

import pandas as pd
import numpy as np

In [2]:
# --- 1. Load Dataset ---
print("Loading Dataset ...")
dataset = pd.read_csv('/Users/victorhugo/Documents/Work/Data Science/Projects/test_a_b/digital_marketing_campaign_dataset.csv')

# --- 2. Shape of dataset ---
print('\n --- Dataset Shape ---')
print(f'dataset: {dataset.shape}')

Loading Dataset ...

 --- Dataset Shape ---
dataset: (8000, 20)

# 2. Exploratory Data Analysis (EDA)

## 2.1. Data Info

In [3]:
dataset.head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,6,9,4,688,IsConfid,ToolConfid,1
1,8001,69,Male,41760,Email,Retention,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,2,7,2,3459,IsConfid,ToolConfid,1
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,11,2,8,2337,IsConfid,ToolConfid,1
3,8003,32,Female,44085,PPC,Conversion,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,2,2,0,2463,IsConfid,ToolConfid,1
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,6,6,8,4345,IsConfid,ToolConfid,1

In [4]:
summary = pd.DataFrame({
    'Datatype':dataset.dtypes,
    "Non-null count": dataset.notnull().sum(),
    'Unique Values': dataset.nunique(),
    'Missing Values': dataset.isna().sum(),
    'Missing %' : (dataset.isna().sum()/ len(dataset))*100
})

summary

,Datatype,Non-null count,Unique Values,Missing Values,Missing %
CustomerID,int64,8000,8000,0,0.0
Age,int64,8000,52,0,0.0
Gender,object,8000,2,0,0.0
Income,int64,8000,7789,0,0.0
CampaignChannel,object,8000,5,0,0.0
CampaignType,object,8000,4,0,0.0
AdSpend,float64,8000,8000,0,0.0
ClickThroughRate,float64,8000,8000,0,0.0
ConversionRate,float64,8000,8000,0,0.0
WebsiteVisits,int64,8000,50,0,0.0
PagesPerVisit,float64,8000,8000,0,0.0
TimeOnSite,float64,8000,8000,0,0.0
SocialShares,int64,8000,100,0,0.0
EmailOpens,int64,8000,20,0,0.0
EmailClicks,int64,8000,10,0,0.0
PreviousPurchases,int64,8000,10,0,0.0
LoyaltyPoints,int64,8000,3983,0,0.0
AdvertisingPlatform,object,8000,1,0,0.0
AdvertisingTool,object,8000,1,0,0.0
Conversion,int64,8000,2,0,0.0

In [5]:
# Data Unbalanced 
dataset['Conversion'].value_counts(normalize = True)

Conversion
1    0.8765
0    0.1235
Name: proportion, dtype: float64

In [6]:
# Features that bring no value: 

advert_plat= dataset['AdvertisingPlatform'].unique()[0]
campaign_channel = dataset['AdvertisingTool'].unique()[0]

print('\n --- Categorical Features with NO variations ---')

no_relevance = pd.DataFrame({
    'Feature': ['AdvertisingPlatform', 'CampaignChannel'],
    'Unique Value': [advert_plat, campaign_channel]
})

print('\n',no_relevance)

 --- Categorical Features with NO variations ---

                Feature Unique Value
0  AdvertisingPlatform     IsConfid
1      CampaignChannel   ToolConfid

In [7]:
# Since these columns bring no predictive value, i will drop them to reduce noise and simplify the modeling


print(" Initial Number of Columns : ", len(dataset.columns) )
excluded_initial_columns = ['AdvertisingPlatform','AdvertisingTool']
print('\n --- Dropped Columns ---')
print(excluded_initial_columns)

dataset = dataset.drop(excluded_initial_columns, axis =1)


print("\n Number of Columns now: ",len(dataset.columns) )

 Initial Number of Columns :  20

 --- Dropped Columns ---
['AdvertisingPlatform', 'AdvertisingTool']

 Number of columns now:  18

In [8]:
dataset['CampaignType'].value_counts(normalize=True)

CampaignType
Conversion       0.259625
Awareness        0.248500
Consideration    0.248500
Retention        0.243375
Name: proportion, dtype: float64