# 1. Setup and Load Data

In [1]:
# ====================================================
# Setup & Imports
# ====================================================

import pandas as pd
import numpy as np

In [2]:
# --- 1. Load Dataset ---
print("Loading Dataset ...")
dataset = pd.read_csv('/Users/victorhugo/Documents/Work/Data Science/Projects/test_a_b/digital_marketing_campaign_dataset.csv')

# --- 2. Shape of dataset ---
print('\n --- Dataset Shape ---')
print(f'dataset: {dataset.shape}')

Loading Dataset ...

 --- Dataset Shape ---
dataset: (8000, 20)

# 2. Exploratory Data Analysis (EDA)

## 2.1. Data Info

In [3]:
dataset.head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,6,9,4,688,IsConfid,ToolConfid,1
1,8001,69,Male,41760,Email,Retention,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,2,7,2,3459,IsConfid,ToolConfid,1
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,11,2,8,2337,IsConfid,ToolConfid,1
3,8003,32,Female,44085,PPC,Conversion,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,2,2,0,2463,IsConfid,ToolConfid,1
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,6,6,8,4345,IsConfid,ToolConfid,1

In [4]:
summary = pd.DataFrame({
    'Datatype':dataset.dtypes,
    "Non-null count": dataset.notnull().sum(),
    'Unique Values': dataset.nunique(),
    'Missing Values': dataset.isna().sum(),
    'Missing %' : (dataset.isna().sum()/ len(dataset))*100
})

summary

,Datatype,Non-null count,Unique Values,Missing Values,Missing %
CustomerID,int64,8000,8000,0,0.0
Age,int64,8000,52,0,0.0
Gender,object,8000,2,0,0.0
Income,int64,8000,7789,0,0.0
CampaignChannel,object,8000,5,0,0.0
CampaignType,object,8000,4,0,0.0
AdSpend,float64,8000,8000,0,0.0
ClickThroughRate,float64,8000,8000,0,0.0
ConversionRate,float64,8000,8000,0,0.0
WebsiteVisits,int64,8000,50,0,0.0
PagesPerVisit,float64,8000,8000,0,0.0
TimeOnSite,float64,8000,8000,0,0.0
SocialShares,int64,8000,100,0,0.0
EmailOpens,int64,8000,20,0,0.0
EmailClicks,int64,8000,10,0,0.0
PreviousPurchases,int64,8000,10,0,0.0
LoyaltyPoints,int64,8000,3983,0,0.0
AdvertisingPlatform,object,8000,1,0,0.0
AdvertisingTool,object,8000,1,0,0.0
Conversion,int64,8000,2,0,0.0

In [5]:
# Data Unbalanced 
dataset['Conversion'].value_counts(normalize = True)

Conversion
1    0.8765
0    0.1235
Name: proportion, dtype: float64

In [6]:
# Features that bring no value: 

advert_plat= dataset['AdvertisingPlatform'].unique()[0]
campaign_channel = dataset['AdvertisingTool'].unique()[0]

print('\n --- Categorical Features with NO variations ---')

no_relevance = pd.DataFrame({
    'Feature': ['AdvertisingPlatform', 'CampaignChannel'],
    'Unique Value': [advert_plat, campaign_channel]
})

print('\n',no_relevance)

 --- Categorical Features with NO variations ---

                Feature Unique Value
0  AdvertisingPlatform     IsConfid
1      CampaignChannel   ToolConfid

In [9]:
# Since these columns bring no predictive value, i will drop them to reduce noise and simplify the modeling


print(" Initial Number of Columns : ", len(dataset.columns) )
excluded_initial_columns = ['CustomerID','AdvertisingPlatform','AdvertisingTool']
print('\n --- Dropped Columns ---')
print(excluded_initial_columns)

dataset = dataset.drop(excluded_initial_columns, axis =1)


print("\n Number of Columns now: ",len(dataset.columns) )

 Initial Number of Columns :  20

 --- Dropped Columns ---
['CustomerID', 'AdvertisingPlatform', 'AdvertisingTool']

 Number of Columns now:  17

In [10]:
# Separating Categorical and Numeric Columns

num_features = [
    col for col in dataset.select_dtypes(include=np.number).columns
    if col not in excluded_initial_columns
]

cat_features = [
    col for col in dataset.select_dtypes(exclude=np.number).columns
    if col not in excluded_initial_columns
]

print('=== NUMERIC FEATURES (incl. CustomerID) ===')
print(f"Count: {len(num_features)}")
print(num_features)

print('\n=== CATEGORICAL FEATURES ===')
print(f"Count: {len(cat_features)}")
print(cat_features)

=== NUMERIC FEATURES (incl. CustomerID) ===
Count: 14
['Age', 'Income', 'AdSpend', 'ClickThroughRate', 'ConversionRate', 'WebsiteVisits', 'PagesPerVisit', 'TimeOnSite', 'SocialShares', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints', 'Conversion']

=== CATEGORICAL FEATURES ===
Count: 3
['Gender', 'CampaignChannel', 'CampaignType']

In [11]:
dataset.describe()

,Age,Income,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,Conversion
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,43.625500,84664.196750,5000.944830,0.154829,0.104389,24.751625,5.549299,7.727718,49.799750,9.476875,4.467375,4.485500,2490.268500,0.876500
std,14.902785,37580.387945,2838.038153,0.084007,0.054878,14.312269,2.607358,4.228218,28.901165,5.711111,2.856564,2.888093,1429.527162,0.329031
min,18.000000,20014.000000,100.054813,0.010005,0.010018,0.000000,1.000428,0.501669,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,51744.500000,2523.221165,0.082635,0.056410,13.000000,3.302479,4.068340,25.000000,5.000000,2.000000,2.000000,1254.750000,1.000000
50%,43.000000,84926.500000,5013.440044,0.154505,0.104046,25.000000,5.534257,7.682956,50.000000,9.000000,4.000000,4.000000,2497.000000,1.000000
75%,56.000000,116815.750000,7407.989369,0.228207,0.152077,37.000000,7.835756,11.481468,75.000000,14.000000,7.000000,7.000000,3702.250000,1.000000
max,69.000000,149986.000000,9997.914781,0.299968,0.199995,49.000000,9.999055,14.995311,99.000000,19.000000,9.000000,9.000000,4999.000000,1.000000

# 2.2 Categorical Features

In [12]:
# Cross-tab analysis: Categorical vs Conversion
print("=== CATEGORICAL FEATURES vs CONVERSION ===\n")

cols = 2
nums = len(cat_features)